# Generated by Django 4.2.4 on 2023-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsiteinfo',
            name='site_icon',
        ),
        migrations.AddField(
            model_name='generalsiteinfo',
            name='site_name',
            field=models.CharField(default='pouria', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to='images/resume/'),
        ),
    ]
